sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.0"
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
cache:
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - export CI=false
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: yarn build
  on:
    branch: ["master"]
